//
//  URLConsts.h
//  Config
//
//  Created by StoneArk on 15/3/31.
//  Copyright (c) 2015年 StoneArk. All rights reserved.
//

/// API 常量表

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString* const API_ADVERTISE_LIST;
FOUNDATION_EXPORT NSString* const API_SUBJECT_ADVERTISE_LIST;
FOUNDATION_EXPORT NSString* const API_ANNOUNCE_ADVERTISE_LIST;

FOUNDATION_EXPORT NSString* const API_MENU_LIST;
FOUNDATION_EXPORT NSString* const API_ARTICLE_LIST;
FOUNDATION_EXPORT NSString* const API_SUBJECT_ARTICLE_LIST;
FOUNDATION_EXPORT NSString* const API_ANNOUNCE_ARTICLE_LIST;
FOUNDATION_EXPORT NSString* const API_DISCUSS_LIST;
FOUNDATION_EXPORT NSString* const API_DISCUSS_NEW;
FOUNDATION_EXPORT NSString* const API_DISCUSS_DELETE;
FOUNDATION_EXPORT NSString* const API_REPLY_LIST;
FOUNDATION_EXPORT NSString* const API_REPLY_INFO;
FOUNDATION_EXPORT NSString* const API_REPLY_DETAIL;
FOUNDATION_EXPORT NSString* const API_REPLY_DELETE;

FOUNDATION_EXPORT NSString* const API_GET_VERIFICATION;
FOUNDATION_EXPORT NSString* const API_GET_VOICE_VERIFICATION;
FOUNDATION_EXPORT NSString* const API_VERIFICATE;

FOUNDATION_EXPORT NSString* const API_FILE_UPLOAD;
FOUNDATION_EXPORT NSString* const API_USER_REGISTER;
FOUNDATION_EXPORT NSString* const API_USER_CHANGE_PASSWORD;
FOUNDATION_EXPORT NSString* const API_USER_CHANGE_HEAD;
FOUNDATION_EXPORT NSString* const API_USER_CHANGE_NICKNAME;
FOUNDATION_EXPORT NSString* const API_USER_RESET_PASSWORD;
FOUNDATION_EXPORT NSString* const API_USER_LOGIN;
FOUNDATION_EXPORT NSString* const API_USER_INFO;
FOUNDATION_EXPORT NSString* const API_USER_LOGOUT;
FOUNDATION_EXPORT NSString* const API_USER_CONFIRM;
FOUNDATION_EXPORT NSString* const API_COMPANY_BIND;
FOUNDATION_EXPORT NSString* const API_COMPANY_EDIT;
FOUNDATION_EXPORT NSString* const API_COMPANY_UNBIND;

FOUNDATION_EXPORT NSString* const API_ARTICLE_HTML;
FOUNDATION_EXPORT NSString* const API_DISCUSS_HTML;
FOUNDATION_EXPORT NSString* const API_VIDEO_HTML;
FOUNDATION_EXPORT NSString* const API_QUESTION_HTML;
FOUNDATION_EXPORT NSString* const API_MESSAGE_LIST;

FOUNDATION_EXPORT NSString* const API_FAVOURITE_LIST;
FOUNDATION_EXPORT NSString* const API_FAVOURITE_ADD;
FOUNDATION_EXPORT NSString* const API_FAVOURITE_DELETE;

FOUNDATION_EXPORT NSString* const API_MESSAGE_DELETE;
FOUNDATION_EXPORT NSString* const API_HELP_HOME;
FOUNDATION_EXPORT NSString* const API_HELP_LIST;
FOUNDATION_EXPORT NSString* const API_HELP_QUESTION_LIST;
FOUNDATION_EXPORT NSString* const API_HELP_VIDEO_LIST;
FOUNDATION_EXPORT NSString* const API_HELP_QUESTION_SEARCH;
FOUNDATION_EXPORT NSString* const API_HELP_COLOR_LIST;

FOUNDATION_EXPORT NSString* const API_SUBJECT_QUESTION_LIST;
FOUNDATION_EXPORT NSString* const API_SUBJECT_VIDEO_LIST;
FOUNDATION_EXPORT NSString* const API_HOME_QUESTION_LIST;

FOUNDATION_EXPORT NSString* const API_KEYWORD_LIST;
FOUNDATION_EXPORT NSString* const API_USER_LOGIN_SUCCESS;
FOUNDATION_EXPORT NSString* const API_SHARE_NOTIFY;
FOUNDATION_EXPORT NSString* const API_GET_LAUNCH_IMAGE;
