//
//  AppConfig.h
//  Config
//
//  Created by StoneArk on 15/3/31.
//  Copyright (c) 2015年 StoneArk. All rights reserved.
//

/// 应用配置常量表

#import <Foundation/Foundation.h>

#define CONFIG_API_ROOT_URL [NSURL URLWithString:CONFIG_API_ROOT]

FOUNDATION_EXPORT NSString* const CONFIG_API_ROOT;
FOUNDATION_EXPORT NSString* const CONFIG_ALIYUN_OSS_BUCKET_NAME;
FOUNDATION_EXPORT NSString* const CONFIG_ALIYUN_OSS_HOST_ID;
FOUNDATION_EXPORT NSString* const CONFIG_ALIYUN_OSS_ACCESS_KEY;
FOUNDATION_EXPORT NSString* const CONFIG_ALIYUN_OSS_SECRET;
FOUNDATION_EXPORT NSString* const CONFIG_UMENG_APP_KEY;
FOUNDATION_EXPORT NSString* const CONFIG_WECHAT_APP_ID;
FOUNDATION_EXPORT NSString* const CONFIG_WECHAT_APP_SECRET;
FOUNDATION_EXPORT NSString* const CONFIG_QQ_APP_ID;
FOUNDATION_EXPORT NSString* const CONFIG_QQ_APP_KEY;
FOUNDATION_EXPORT NSString* const CONFIG_SHARE_URL;
FOUNDATION_EXPORT NSString* const CONFIG_SHARE_TITLE;
